const ActionType = {
  SESSION_CONNECTING: 'SESSION_CONNECTING',
  SESSION_OPENED: 'SESSION_OPENED',
  SESSION_CLOSED: 'SESSION_CLOSED',
  SESSION_ERROR: 'SESSION_ERROR',
};

export default ActionType;
