const ActionType = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  MACHINES_FETCH_SUCCESS: 'MACHINES_FETCH_SUCCESS',
  MACHINE_SELECT: 'MACHINE_SELECT',
};

export default ActionType;
